# Start with a base image that has Python installed, as Ansible is Python-based
FROM python:3.8-slim

# Install Ansible via pip
RUN pip install --no-cache-dir ansible

# Copy your Ansible configuration, playbooks, roles, and inventory into the container
COPY ./ansible/ /ansible/

# Set working directory to /ansible where your Ansible playbooks are located
WORKDIR /ansible

# Ensure the .ssh directory exists
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

# By default, run ansible-playbook command
CMD ["ansible-playbook", "-i", "inventories/setup.yml", "playbook.yml"]
