name: CI devops 2023
on:
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # 检出您的 GitHub 代码
      - uses: actions/checkout@v2.5.0

      # 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 使用 Maven 构建和测试应用程序
      - name: Build and test with Maven
        run: mvn clean verify
